server:
  port: 9193
  servlet:    context-path: /obs-api-client

spring:
  application:
    name: obs-api-client

    
eureka:
  client:
    service-url: 
     defaultZone: http://localhost:9191/eureka
  instance:    prefer-ip-address: true
